baseURL = "https://cookforit.com/"
theme = "risotto"
title = "cookforit"
author = "Perrr51"
copyright = "© [Perrr51](https://Cookforit)"
paginate = 3
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = true

[languages]
[languages.es]
  languageName = "Español"
  weight = 1
  title = "cookforit"
  contentDir = "content/es/"

  [languages.es.menu]
  
  [[languages.es.menu.main]]
  name = "post"
  url = "/es/post/"
  weight = 1

  [[languages.es.menu.main]]
  name = "proyectos"
  url = "/es/proyectos/"
  weight = 2

  [[languages.es.menu.main]]
  name = "Estudios actuales"
  url = "/es/Estudios actuales/"
  weight = 3

[languages.en]
  languageName = "English"
  weight = 2
  title = "cookforit"
  contentDir = "content/en/"

  [languages.en.menu]
  
  [[languages.en.menu.main]]
  name = "Posts"
  url = "/en/post/"
  weight = 1

  [[languages.en.menu.main]]
  name = "Projects"
  url = "/en/project/"
  weight = 2

  [[languages.en.menu.main]]
  name = "Current Studies"
  url = "/en/current_studies/"
  weight = 3


enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "tokyo-night-dark"

# Sidebar: about/bio
[params.about]
title = "CookFOR(IT)"
description = "Simple blog"
# unicode/emoji logo:
logo = "🍚"
# or use an image:
#logo_image = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Perrr51"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:example@example.com"

[[params.socialLinks]]
icon = "ai ai-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0001-2345-6789"

[menu]


 #[[menu.main]]
  #identifier = "about"
   #name = "About"
    #url = "/about/"
    #eight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
